module.exports = {
  menu: [
    {
      "title": "学生管理",
      "name": "students",
      "icon": "user1",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "学生列表",
          "name": "students_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增学生",
          "name": "students_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑学生",
          "name": "students_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },

        {
          "title": "学习记录列表",
          "name": "learning_record_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },

        {
          "title": "观看进度列表",
          "name": "watch_progress_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "观看进度详情",
          "name": "watch_progress_details",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
      ]
    },
    {
      "title": "教学资源管理",
      "name": "resource",
      "icon": "file",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "视频列表",
          "name": "videos_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增视频",
          "name": "videos_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑视频",
          "name": "videos_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },

        {
          "title": "教学课件列表",
          "name": "courseware_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增教学课件",
          "name": "courseware_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑教学课件",
          "name": "courseware_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },

        {
          "title": "教学大纲列表",
          "name": "syllabus_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增教学大纲",
          "name": "syllabus_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑教学大纲",
          "name": "syllabus_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
      ]
    },
    {
      "title": "房产管理",
      "name": "house",
      "icon": "house",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "房源列表",
          "name": "house_list",
          "icon": "",
          "cache": true,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增房源",
          "name": "add_house",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "编辑房源",
          "name": "edit_house",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "房产大数据",
          "name": "house_big_data",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "卖家信息",
          "name": "seller_info",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        }
      ]
    },
    {
      "title": "视频管理",
      "name": "video",
      "icon": "video",
      "cache": false,
      "hidden": false,
      "iframe": false
    },
    {
      "title": "移民管理",
      "name": "immigration",
      "icon": "immigration",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "移民项目列表",
          "name": "immigration_list",
          "icon": "",
          "cache": true,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增移民项目",
          "name": "add_immigration",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "编辑移民项目",
          "name": "edit_immigration",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "移民类型管理",
          "name": "immigration_type",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        }
      ]
    },
    {
      "title": "城市管理",
      "name": "city",
      "icon": "city",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "城市列表",
          "name": "city_list",
          "icon": "",
          "cache": true,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增城市",
          "name": "add_city",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "编辑城市",
          "name": "edit_city",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        }
      ]
    },
    {
      "title": "文章管理",
      "name": "article",
      "icon": "article",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "投资指南",
          "name": "investment_guide",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "资讯管理",
          "name": "information",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "物业管理",
          "name": "property_management",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "贷款流程",
          "name": "loans_process",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "购房流程",
          "name": "purchase_process",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "卖房流程",
          "name": "sell_process",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        }
      ]
    },
    {
      "title": "标签管理",
      "name": "label",
      "icon": "label",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "热门房源标签",
          "name": "house_label",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "视频看房标签",
          "name": "video_label",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "商业地产标签",
          "name": "business_label",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "投资指南标签",
          "name": "guide_label",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "资讯管理标签",
          "name": "information_label",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        }
      ]
    },
    {
      "title": "表单管理",
      "name": "form",
      "icon": "form",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "首页表单",
          "name": "home_form",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "关于我们表单",
          "name": "about_form",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "加入我们表单",
          "name": "join_form",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "市场报告表单",
          "name": "bazaar_form",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "卖房流程表单",
          "name": "process_form",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        }
      ]
    },
    {
      "title": "问题管理",
      "name": "issue",
      "icon": "issue",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "问题详情",
          "name": "issue_details",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "栏目管理",
          "name": "issue_column",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        }
      ]
    },
    {
      "title": "网站管理",
      "name": "website",
      "icon": "website",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "轮播图管理",
          "name": "slideshow",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "图片管理",
          "name": "picture",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "二维码管理",
          "name": "QR_code",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "底部栏管理",
          "name": "footer",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        }
      ]
    },
    {
      "title": "关于我们",
      "name": "about_us",
      "icon": "about",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "世帆介绍",
          "name": "introduce",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "合作成员",
          "name": "cooperation",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "联系我们",
          "name": "contact_us",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        }
      ]
    }
  ]
}
