module.exports = {
  menu: [
    {
      "title": "学生管理",
      "name": "students",
      "icon": "user1",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "学生列表",
          "name": "students_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增学生",
          "name": "students_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑学生",
          "name": "students_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },

        {
          "title": "学习记录列表",
          "name": "learning_record_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },

        {
          "title": "观看进度列表",
          "name": "watch_progress_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "观看进度详情",
          "name": "watch_progress_details",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
      ]
    },
    {
      "title": "教学资源管理",
      "name": "resource",
      "icon": "file",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "视频列表",
          "name": "videos_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增视频",
          "name": "videos_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑视频",
          "name": "videos_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },

        {
          "title": "教学课件列表",
          "name": "courseware_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增教学课件",
          "name": "courseware_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑教学课件",
          "name": "courseware_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },

        {
          "title": "教学大纲列表",
          "name": "syllabus_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增教学大纲",
          "name": "syllabus_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑教学大纲",
          "name": "syllabus_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
      ]
    },
    {
      "title": "题库管理",
      "name": "examination",
      "icon": "examination",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "客观题列表",
          "name": "choice_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增客观题",
          "name": "choice_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑客观题",
          "name": "choice_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },

        {
          "title": "主观题列表",
          "name": "subject_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增主观题",
          "name": "subject_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑主观题",
          "name": "subject_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },

        {
          "title": "模拟考试列表",
          "name": "testing_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增模拟考试",
          "name": "testing_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑模拟考试",
          "name": "testing_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
      ]
    },
    {
      "title": "作业管理",
      "name": "homework",
      "icon": "homework",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "作业列表",
          "name": "homework_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "新增作业",
          "name": "homework_add",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
        {
          "title": "编辑作业",
          "name": "homework_edit",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },

        {
          "title": "提交列表",
          "name": "homework_info_list",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "作业提交详情",
          "name": "homework_info_details",
          "icon": "",
          "cache": false,
          "hidden": true,
          "iframe": false,
        },
      ]
    },
    {
      "title": "师生互动管理",
      "name": "interaction",
      "icon": "interaction",
      "cache": false,
      "hidden": false,
      "iframe": false,
    },
    {
      "title": "评价管理",
      "name": "evaluate",
      "icon": "evaluate",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "校内专家评价",
          "name": "remark_in",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "校外专家评价",
          "name": "remark_out",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "学生评价",
          "name": "remark_student",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "教师评价",
          "name": "remark_teacher",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
      ]
    },
    {
      "title": "网站管理",
      "name": "website",
      "icon": "website2",
      "cache": false,
      "hidden": false,
      "iframe": false,
      "children": [
        {
          "title": "图片管理",
          "name": "images",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "简介信息",
          "name": "intro",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
        {
          "title": "教学团队",
          "name": "team",
          "icon": "",
          "cache": false,
          "hidden": false,
          "iframe": false,
        },
      ]
    }
  ]
}
